In [15]:
#1D array perations indexing/silicing
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)
x.dtype
#indexing and assigning values
x[2]=0
print(x)
# silicing and assiging value
print(x[5:8])
x[5:8]=12
print(x[5:8])
# it is a view so what ever changes made on the index or silicing will be imapacted to source array.
# The value is propagated to entire selection
print(x)


[1 2 3 4 5 6 7 8 9]
[1 2 0 4 5 6 7 8 9]
[6 7 8]
[12 12 12]
[ 1  2  0  4  5 12 12 12  9]


In [33]:
#2D array perations indexing/silicing
import numpy as np
y=np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])
print(y)
#indexing and assigning values
#In 2d scalar indexing will refer lists in it.
print(y[1])
#To index single elements in 2D then we need to use [row-axis,column-axis]
print(y[1,0])
#Silicing and assiging value
#row axis silicing 
print(y[:2])
#Column silicing 
print(y[:2,:2])
# Assignment to the selection 
y[:2,:2]=12
print(y[:2,:2])
# it is a view so what ever changes made on the index or silicing will be imapacted to source array.
# The value is propagated to entire selection
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
[5 6 7 8]
5
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [5 6]]
[[12 12]
 [12 12]]
[[12 12  3  4]
 [12 12  7  8]
 [ 8  9 10 11]]


In [36]:
#3D array perations indexing/silicing
import numpy as np
z=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(z)
#indexing and assigning values
#In 3d scalar indexing will refer lists in it.
print(z[1])
#To index single elements in 2D then we need to use [row-axis,column-axis]
print(z[1,0])
#Silicing and assiging value
#row axis silicing 
t=z[1]
print(t[:2])
#Column silicing 
print(t[:2,:2])
# Assignment to the selection 
t[:2,:2]=12
print(t[:2,:2])
# it is a view so what ever changes made on the index or silicing will be imapacted to source array.
# The value is propagated to entire selection
print(z)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[[ 9 10 11 12]
 [13 14 15 16]]
[ 9 10 11 12]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10]
 [13 14]]
[[12 12]
 [12 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[12 12 11 12]
  [12 12 15 16]]]
[5 6 7 8]
